# 7/7

### 판다스

- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)
- Contents
    - Series(변환, 인덱스 구조, 원소 선택)
    - DataFrame(변환, 행인덱스/열이름 지정, 삭제, 선택(###특정조건), 추가, 변경, 전치(###행과 열 바꿈), 인덱스 활용)

- 시리즈와 데이터프레임은 판다스에 들어있는 class  
- 판다스는 데이터 전처리할 때 중요한 tool

In [1]:
# 설정 값을 바꿔서 출력될 표의 크기를 바꿀 수 있음.

# 최대 출력 행 수를 10행으로 제한
import pandas as pd

# pd.options.display.max_rows = 10
pd.set_option('max_rows', 10) # 1~10
df = pd.DataFrame({'x':range(150)})
df

x
0      0
1      1
2      2
3      3
4      4
..   ...
145  145
146  146
147  147
148  148
149  149

[150 rows x 1 columns]

In [3]:
# 최대 열 수를 설정

pd.options.display.max_columns = 20

import seaborn as sns
data = sns.load_dataset('titanic')
data

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [4]:
# 시리즈 클래스 만들기
import pandas as pd

# k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1,'b':2,'c':3}

sr = pd.Series(dict_data) ### 시리즈로 만들어줌(하나의 열)
print(sr)
type(sr)

a    1
b    2
c    3
dtype: int64


pandas.core.series.Series

In [5]:
dict_data = {'a':1,'b':2,'c':3}

# 키 값이 컬럼으로 / 인덱스 지정해주기
df3 = pd.DataFrame(dict_data,index=list('123'))

df3

a  b  c
1  1  2  3
2  1  2  3
3  1  2  3

In [6]:
# 리스트를 시리즈로 변환
import pandas as pd

list_data = ['2019-07-02',3.14,'ABC',100,True]
sr = pd.Series(list_data)
sr

0    2019-07-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [7]:
import pandas as pd

list_data = ['2019-07-02',3.14,'ABC',100,True]
sr = pd.Series(list_data, index=list('abcde')) # 인덱스 지정
sr

a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [9]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx) # 타입 : 인덱스 / 인덱싱가능
print(val) # 배열로 나옴

RangeIndex(start=0, stop=5, step=1)
['2019-07-02' 3.14 'ABC' 100 True]


In [10]:
# 튜플을 시리즈로 변환

tup_data = ('kevin','2019-07-02','남',True)
sr = pd.Series(tup_data, index = ['이름','생년월일','성별','학생여부'])
sr

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object

In [11]:
# 인덱싱
print(sr[0])
print(sr['이름'])

print("-"*50)

print(sr[[1,2]]) ### 여러 개 주려면 리스트 형태로 넣기

kevin
kevin
--------------------------------------------------
생년월일    2019-07-02
성별               남
dtype: object


In [12]:
# 넘파이로 배열 만들기

import numpy as np
s1 = np.arange(11,16)
print(s1, type(s1))

print("-"*50)

s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'>
--------------------------------------------------
a    11
b    12
c    13
d    14
e    15
dtype: int64 <class 'pandas.core.series.Series'>


In [13]:
import numpy as np
s1 = np.arange(11,21,2) # 세번째는 간격
print(s1, type(s1))

print("-"*50)

s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>
--------------------------------------------------
a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


Q. 배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요.  
  
Califonia    1000  
Ohio         2000  
Oregon       3000  
Texas        4000  
Name: population, dtype: int32  

In [14]:
import numpy as np
import pandas as pd

s1 = np.arange(1000,5000,1000)
s2 = pd.Series(s1, index=['Califonia','Ohio','Oregon','Texas'], name = "population")
print(s2)

Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


In [16]:
import numpy as np
import pandas as pd

data = np.arange(1000,5000,1000)
state = ['Califonia','Ohio','Oregon','Texas']
obj = pd.Series(data, index=state, name='population')
obj.name = 'population'
obj.index.name = 'state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64

In [17]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [18]:
# null값 있는지 확인
obj.isnull()

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [19]:
# null의 개수
obj.isnull().sum()

1

#### 데이터프레임
- 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
- 데이터프레임의 열은 각각 시리즈 객체.
- 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
- 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
- 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
- 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

<img src = '벡터.jpg' STYLE='width 500px;'>

In [20]:
# 배열을 데이터프레임으로 변환
np.random.seed(0) # 랜덤 값 고정
data = np.random.randint(100,120,size=(3,3))
print(data, type(data))

df = pd.DataFrame(data,index=['d1','d2','d3'],
                 columns = ['pd','sales','inv'])

df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [21]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스
print(df.iloc[1]) # 시리즈로 출력됨
print('-'*50)
print(df.loc['d2'])
print('-'*50)
print(df.iloc[1].loc['pd'])
print('-'*50)
print(df.iloc[1,0])
print('-'*50)
print(df.loc['d2','pd'])
print('-'*50)
print(df.pd)

pd       103
sales    103
inv      107
Name: d2, dtype: int64
--------------------------------------------------
pd       103
sales    103
inv      107
Name: d2, dtype: int64
--------------------------------------------------
103
--------------------------------------------------
103
--------------------------------------------------
103
--------------------------------------------------
d1    112
d2    103
d3    109
Name: pd, dtype: int64


In [22]:
df.iloc[2]=0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [23]:
df.loc['d3']=0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [26]:
# 없는 인덱스 -> 추가됨
df.loc['d4'] = 1
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    1      1    1

In [27]:
df.columns

Index(['pd', 'sales', 'inv'], dtype='object')

In [28]:
# id, gender, age, region

import random
id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,101, size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)


df = pd.concat([i1,g1,a1,r1],axis=1) # 열방향 합치기 : axis = 1 / 행방향 합치기 : axis = 0
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'},inplace=True) # inplace = True는 원본에 반영
df

id  gender  age  region
0       1       0   11      10
1       2       1   68      10
2       3       0    7       7
3       4       0   92      10
4       5       0  100      10
..    ...     ...  ...     ...
995   996       0   73       8
996   997       1    6       4
997   998       1   40       6
998   999       0   80       7
999  1000       0   80       5

[1000 rows x 4 columns]

In [51]:
# copy
df1 = df[:]

df1 = df.copy()
df1

id  gender  age  region
0       1       0   11      10
1       2       1   68      10
2       3       0    7       7
3       4       0   92      10
4       5       0  100      10
..    ...     ...  ...     ...
995   996       0   73       8
996   997       1    6       4
997   998       1   40       6
998   999       0   80       7
999  1000       0   80       5

[1000 rows x 4 columns]

In [29]:
df1 = df.copy()
df1.head(3) # 앞 행
# df1.tail(3) # 뒷 행

id  gender  age  region
0   1       0   11      10
1   2       1   68      10
2   3       0    7       7

In [31]:
df1.iloc[:2] = np.nan
df1.head()

id  gender    age  region
0  NaN     NaN    NaN     NaN
1  NaN     NaN    NaN     NaN
2  3.0     0.0    7.0     7.0
3  4.0     0.0   92.0    10.0
4  5.0     0.0  100.0    10.0

In [32]:
import numpy as np
import pandas as pd

a = np.random.randint(1,5,size=(10,5))
print(a,type(a))

[[2 1 4 1 3]
 [3 4 1 3 3]
 [2 1 1 2 3]
 [2 2 2 3 4]
 [4 4 2 4 1]
 [4 3 2 2 4]
 [2 2 2 2 1]
 [3 1 4 4 2]
 [2 4 2 1 2]
 [1 3 1 4 4]] <class 'numpy.ndarray'>


In [33]:
# 2차원 리스트를 데이터프레임으로 변환
list1 = a.tolist()
print(list1,type(list1))
df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
df1.head(3)

[[2, 1, 4, 1, 3], [3, 4, 1, 3, 3], [2, 1, 1, 2, 3], [2, 2, 2, 3, 4], [4, 4, 2, 4, 1], [4, 3, 2, 2, 4], [2, 2, 2, 2, 1], [3, 1, 4, 4, 2], [2, 4, 2, 1, 2], [1, 3, 1, 4, 4]] <class 'list'>


c1  c2  c3  c4  c5
0   2   1   4   1   3
1   3   4   1   3   3
2   2   1   1   2   3

In [34]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df1.values # 데이터프레임 -> 배열로 바뀜
print(ar,type(ar))

li = ar.tolist() # 배열 -> 리스트로 바뀜
print(li,type(li))

dict = df1.to_dict() # 딕셔너리로 바뀜(데이터프레임에서 바꾸기. 배열에서 바꾸는건 X)
print(dict,type(dict))

[[2 1 4 1 3]
 [3 4 1 3 3]
 [2 1 1 2 3]
 [2 2 2 3 4]
 [4 4 2 4 1]
 [4 3 2 2 4]
 [2 2 2 2 1]
 [3 1 4 4 2]
 [2 4 2 1 2]
 [1 3 1 4 4]] <class 'numpy.ndarray'>
[[2, 1, 4, 1, 3], [3, 4, 1, 3, 3], [2, 1, 1, 2, 3], [2, 2, 2, 3, 4], [4, 4, 2, 4, 1], [4, 3, 2, 2, 4], [2, 2, 2, 2, 1], [3, 1, 4, 4, 2], [2, 4, 2, 1, 2], [1, 3, 1, 4, 4]] <class 'list'>
{'c1': {0: 2, 1: 3, 2: 2, 3: 2, 4: 4, 5: 4, 6: 2, 7: 3, 8: 2, 9: 1}, 'c2': {0: 1, 1: 4, 2: 1, 3: 2, 4: 4, 5: 3, 6: 2, 7: 1, 8: 4, 9: 3}, 'c3': {0: 4, 1: 1, 2: 1, 3: 2, 4: 2, 5: 2, 6: 2, 7: 4, 8: 2, 9: 1}, 'c4': {0: 1, 1: 3, 2: 2, 3: 3, 4: 4, 5: 2, 6: 2, 7: 4, 8: 1, 9: 4}, 'c5': {0: 3, 1: 3, 2: 3, 3: 4, 4: 1, 5: 4, 6: 1, 7: 2, 8: 2, 9: 4}} <class 'dict'>


In [35]:
# file 생성
file_data = pd.DataFrame({
    'col1':[1,2,3,4,5,6]
    ,'col2':['A','A','B','B','C','C']
})
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [37]:
file_data.to_csv('file_data.csv',index=None)
file_data=pd.read_csv('file_data.csv')
print(file_data,type(file_data))

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C <class 'pandas.core.frame.DataFrame'>


In [38]:
import pandas as pd
import numpy as np

df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1)
print(df_2)

   col1 col2
0     1    A
1     2    B
2     3    C
   col1 col2
0     4    D
1     5    E
2     6    F


In [39]:
# Q. df_1과 df_2를 행방향과 열방향으로 병합하여 출력하세요.

df_3 = pd.concat([df_1,df_2],axis=1) # 열방향
df_4 = pd.concat([df_1,df_2]) # 행방향(default)
print(df_3)
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F
   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [40]:
# 데이터 추출
print(df_4.col2, type(df_4.col2)) # 컬럼 하나만 뽑으면 Series
print('-'*50)

print(df_4['col2'], type(df_4['col2']))

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object <class 'pandas.core.series.Series'>
--------------------------------------------------
0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object <class 'pandas.core.series.Series'>


In [41]:
# 컬럼 하나만 뽑을 때 Series가 아닌 DataFrame으로 출력
df = pd.DataFrame(df_4['col2'])
print(df,type(df))
print('-'*50)

print(df_4[['col2']], type(df_4[['col2']]))

  col2
0    A
1    B
2    C
0    D
1    E
2    F <class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
  col2
0    A
1    B
2    C
0    D
1    E
2    F <class 'pandas.core.frame.DataFrame'>


In [42]:
# 열 삭제
df = df1.copy()
df.drop('c1',axis=1) # 컬럼 삭제

c2  c3  c4  c5
0   1   4   1   3
1   4   1   3   3
2   1   1   2   3
3   2   2   3   4
4   4   2   4   1
5   3   2   2   4
6   2   2   2   1
7   1   4   4   2
8   4   2   1   2
9   3   1   4   4

In [43]:
df # 다시 df를 출력해보면 삭제가 안 되어 있음

c1  c2  c3  c4  c5
0   2   1   4   1   3
1   3   4   1   3   3
2   2   1   1   2   3
3   2   2   2   3   4
4   4   4   2   4   1
5   4   3   2   2   4
6   2   2   2   2   1
7   3   1   4   4   2
8   2   4   2   1   2
9   1   3   1   4   4

In [44]:
df = df1.copy()
df_a = df.drop('c1',axis=1) ### 삭제 유지하려면 변수에 저장거나 inplace=True
df_a

c2  c3  c4  c5
0   1   4   1   3
1   4   1   3   3
2   1   1   2   3
3   2   2   3   4
4   4   2   4   1
5   3   2   2   4
6   2   2   2   1
7   1   4   4   2
8   4   2   1   2
9   3   1   4   4

In [45]:
df.head(1)

c1  c2  c3  c4  c5
0   2   1   4   1   3

In [46]:
df.query('c3==2') # c3열에서 2인 값만 출력

c1  c2  c3  c4  c5
3   2   2   2   3   4
4   4   4   2   4   1
5   4   3   2   2   4
6   2   2   2   2   1
8   2   4   2   1   2

In [51]:
df.query("c3==3 & c4==1") # 동시에 조건 충족

Empty DataFrame
Columns: [c1, c2, c3, c4, c5]
Index: []

In [52]:
df.query('c3==(2,4)')

c1  c2  c3  c4  c5
0   2   1   4   1   3
3   2   2   2   3   4
4   4   4   2   4   1
5   4   3   2   2   4
6   2   2   2   2   1
7   3   1   4   4   2
8   2   4   2   1   2

In [53]:
df.query('c3==2|c4==1') # 하나 이상 조건 충족

c1  c2  c3  c4  c5
0   2   1   4   1   3
3   2   2   2   3   4
4   4   4   2   4   1
5   4   3   2   2   4
6   2   2   2   2   1
8   2   4   2   1   2

In [54]:
df.query('c3==3')[["c3","c4"]] # c3가 3인 c3와 c4 데이터 추출

Empty DataFrame
Columns: [c3, c4]
Index: []

In [55]:
help(df.query) ### 도움말

Help on method query in module pandas.core.frame:

query(expr: 'str', inplace: 'bool' = False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that are not valid Python variable names
        by surrounding them in backticks. Thus, column names containing spaces
        or punctuations (besides underscores) or starting with digits must be
        surrounded by backticks. (For example, a column named "Area (cm^2)" would
        be referenced as ```Area (cm^2)```). Column names which are Python keywords
        (like "list", "for", "import", etc) cannot be used.
    
        For example, if one of your columns is called ``a a`` and you want
        to sum it

In [56]:
df.rename(columns = {'c1':'국어','c2':'영어','c3':'수학','c4':'사회','c5':'과학'})

국어  영어  수학  사회  과학
0   2   1   4   1   3
1   3   4   1   3   3
2   2   1   1   2   3
3   2   2   2   3   4
4   4   4   2   4   1
5   4   3   2   2   4
6   2   2   2   2   1
7   3   1   4   4   2
8   2   4   2   1   2
9   1   3   1   4   4

In [57]:
df_e = df[:]

import warnings
warnings.filterwarnings("ignore")

df_e.rename(columns = {'c1':'국어','c2':'영어','c3':'수학','c4':'사회','5':'과학','c5':'음악'},
          index={0:'권준기',1:'우동주',2:'임희진'},inplace=True)

df_e

국어  영어  수학  사회  음악
권준기   2   1   4   1   3
우동주   3   4   1   3   3
임희진   2   1   1   2   3
3     2   2   2   3   4
4     4   4   2   4   1
5     4   3   2   2   4
6     2   2   2   2   1
7     3   1   4   4   2
8     2   4   2   1   2
9     1   3   1   4   4

In [58]:
df_e.loc['권준기','음악']
df_e.iloc[0,4]

3