# 7/8

# 연산
- 행/열 인덱스를 기준으로 모든 원소를 정렬한다.
- 동일한 위치에 있는 원소끼리 일대일 대응시킨다.
- 일대일 대응이 되는 원소끼리 연산을 처리한다.

In [1]:
import pandas as pd
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})
print(st1)
print(st2)

국어    100
영어     80
수학     90
dtype: int64
수학    80
국어    90
영어    80
dtype: int64


In [2]:
# Series 끼리 연산
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
print(add)
print(type(add))

국어    190
수학    170
영어    160
dtype: int64
<class 'pandas.core.series.Series'>


In [3]:
df = pd.concat([add,sub,mul,div],axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [4]:
df.columns = ['add','sub','mul','div']
df

add  sub   mul   div
국어  190   10  9000  1.11
수학  170   10  7200  1.12
영어  160    0  6400  1.00

In [5]:
# Q. df의 컬럼이름을 add,sub,mul,div으로 변경하여 출력하세요
df.rename(columns={0:'add',1:'sub',2:'mul',3:'div'},inplace=True)
df

add  sub   mul   div
국어  190   10  9000  1.11
수학  170   10  7200  1.12
영어  160    0  6400  1.00

In [6]:
df.columns

Index(['add', 'sub', 'mul', 'div'], dtype='object')

# 7/9

In [7]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [8]:
a = np.arange(10)
print(a,type(a))
print('-'*50)
print(a.reshape(2,5), type(a.reshape(2,5)))
print('-'*50)
print(a.reshape(5,2),type(a.reshape(2,5)))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
--------------------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]] <class 'numpy.ndarray'>
--------------------------------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'>


In [9]:
a = np.arange(12)
b = a.reshape(2,2,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
a = np.arange(12)
print(a)
a.reshape(3,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
df2 = pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [12]:
df1 + df2 # 겹치는 부분은 더해지고, 한 쪽이 없는 부분은 NaN값으로 나옴.

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [13]:
add_data = df1.add(df2,fill_value=0) # df1 (첫 데이터프레임)에서 없는 행과 열의 value를 0으로 지정
add_data

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [14]:
sub_data = df1.sub(df2,fill_value=0)
sub_data

a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0  -1.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0

In [15]:
mul_data = df1.mul(df2,fill_value=0)
mul_data

a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0  30.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0

In [16]:
div_data = df1.div(df2,fill_value=0)  # 0으로 나누면 0이 나오는데, 0을 다른 수로 나누면 NaN나옴.
div_data

# 0으로 나눠지는 경우 등의 예외처리를 해줘야함!

a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8  0.833333  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0

In [17]:
# 계산인자를 뒤집어 계산
1/df1 ### 역수

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [18]:
# 계산인자를 뒤집어 계산
df1.rdiv(1) ### 1/df1 과 같음. x/df=df.rdiv(x)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [19]:
# 행 뽑아옴(시리즈)
print(df1)
s1 = df1.iloc[0]
s1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    0.0
b    1.0
c    2.0
d    3.0
Name: 0, dtype: float64

In [20]:
df1 - s1 # 데이터프레임에서 시리즈를 빼기

a    b    c    d
0  0.0  0.0  0.0  0.0
1  4.0  4.0  4.0  4.0
2  8.0  8.0  8.0  8.0

In [21]:
s2 = df1['d']
s2

0     3.0
1     7.0
2    11.0
Name: d, dtype: float64

In [23]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [22]:
df1.sub(s2,axis=0) ### 계산을 행방향으로 하므로 axis = 0 으로

a    b    c    d
0 -3.0 -2.0 -1.0  0.0
1 -3.0 -2.0 -1.0  0.0
2 -3.0 -2.0 -1.0  0.0