# 7/22

In [1]:
# 파이썬 random 함수
import random
print(random.random()) # 0.0 <= x < 1.0 사이
print(random.randint(1,10)) # min max 사이의 정수중에서 난수값 리턴
print(random.uniform(10,20)) # min max 사이 float 리턴
print(random.randrange(10)) # 지정범위 int 리턴
print(random.choice([1,2,3,4,5])) # 리스트 내부에 있는 요소를 랜덤하게 선택
print(random.sample([1,2,3,4,5],2)) # 리스트 요소를 중복이 안되게 추출해 줌
li=[1,2,3,4,5]
random.shuffle(li)
print(li)

0.7560008989929219
5
13.898052694310904
4
5
[3, 2]
[3, 1, 2, 4, 5]


In [2]:
# 넘파이의 np.random
# rand : 0.0 ~ 1.0 사이의 균일 분포(실수)
# randint : 균일 분포의 정수 난수
# randn : 가우시안 표준 정규 분포
# normal : 정규분포 난수 샘플 (loc, scale, size) <- 여기서 loc는 평균 / scale 은 표준편차

In [3]:
import numpy as np
np.random.seed(0)
np.random.rand(5)
np.random.rand(3,2)

array([[0.64589411, 0.43758721],
       [0.891773  , 0.96366276],
       [0.38344152, 0.79172504]])

In [4]:
np.random.randint(5) # 0 ~ 4까지 정수 난수 1개
np.random.randint(1,20) ### 1 ~ 19까지 정수 난수 1개
np.random.randint(10, size=10) ### 0 ~ 9까지 정수 난수 10개(중복 있음)
np.random.randint(10,20,size=(3,5)) ### 10 ~ 19까지 정수로 3행5열 만들어줌

array([[12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11],
       [19, 19, 10, 14, 17]])

In [5]:
np.random.choice([1,2,3,4,5]) ### 리스트 안에서 1개 뽑음

### 비복원추출(이미 뽑은건 다시 안 넣음)
np.random.choice(5,5,replace=False) ### 앞에 5는 0~4, 뒤 5는 5개 의미 (이것도 중복 안됨!)

#np.random.choice((1,2,3,4,5),5,replace=False) # 동일


### 복원추출
np.random.choice(5,5) ### 이건 중복있음! replace=False를 해줘야 중복안됨

array([0, 0, 4, 0, 4])

In [7]:
list = [0,1,2,3,4]
np.random.shuffle(list)
list

# 위랑 동일!
np.random.choice(5,5,replace=False)

array([3, 1, 0, 4, 2])

In [8]:
import numpy as np
abs(np.random.randn(6))
np.random.randn(3,2)

array([[-1.04855297, -1.42001794],
       [-1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 ]])

In [9]:
# 범위 내 실수 출력
np.random.uniform(1,2,3) # 1 ~ 2 사이 실수 3개 뽑음
np.random.uniform(0,1,(2,3))

array([[0.24442559, 0.15896958, 0.11037514],
       [0.65632959, 0.13818295, 0.19658236]])

In [10]:
# random_sample은 uniform 하수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3)) # random_sample 은 0~1 사이 실수 뽑음

array([[0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947]])