# 8/19

In [12]:
# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기',
         '믹서','믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
print('인코딩 변환값:', labels) # 문자열 순서로 인코딩됨

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [13]:
print('인코딩 클래스:',encoder.classes_) # 0,1,2,3,4,5 순서대로 나옴

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자랜지' '컴퓨터']


In [14]:
print('디코딩 원본 값:',encoder.inverse_transform(labels))
print('디코딩 원본 값:',encoder.inverse_transform([0,1,4,5,3,3,2,2]))

디코딩 원본 값: ['TV' '냉장고' '전자랜지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']
디코딩 원본 값: ['TV' '냉장고' '전자랜지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


In [15]:
# 원-핫 인코딩
### 회귀에서 숫자의 크기가 영향을 줄 수 있을 때는 쓰면 안되고, 
### 분류형은 숫자의 크기가 의미가 없기 때문에 쓸 수 있음
### 원-핫 인코딩 -> 독립변수가 너무 많아짐. 독립변수가 많아지면 별 의미가 없더라도 설명력이 높아짐.
### 수정결정계수로 변수 수 보정한 수정결정계수가 있음

### 따라서 규제를 적용(리치모델 / 라쏘모델) : 변수의 계수에 패널티 줌으로써 보정(독립변수가 추가되면서 설명력이 높아지는것에 패널티)

In [16]:
# 원-핫 인코딩
### 원-핫 인코딩은 레이블인코딩을 한 후에 해야함
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자랜지','컴퓨터','선풍기','선풍기',
         '믹서','믹서']
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels = labels.reshape(-1,1) # 2차배열(1열)로 바꿔줌
labels

oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)
print('웟-핫 인코딩:')
print(oh_labels.toarray()) # 희소행렬(나머지는 0, 해당되는건 1)

웟-핫 인코딩:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
